Repository snabbco/snabb, pull requests merged in 2022-01, with the labels that each got.

#1466 Fixes for regressions in max-next headed for Octarina release
  src/core/app.lua
  src/core/main.lua
  src/core/packet.lua
  src/lib/ptree/worker.lua
  src/lib/scheduling.lua
  src/program/lwaftr/migrate_configuration/migrate_configuration.lua
  src/program/lwaftr/tests/config-migrations/selftest.sh
  src/program/snabbnfv/traffic/traffic.lua
Labels: merged, release-octarina

#1452 Various YANG fixes related to choice statements and the consistency checker
  src/lib/yang/data.lua
  src/lib/yang/path_data.lua
  src/program/config/common.lua
Labels: merged, release-octarina

#1455 lib.numa: gracefully handle failure to read CPU performance governor
  src/lib/numa.lua
Labels: merged, release-octarina

#1456 lib.ptree: cleanup obsolete aggregated stats
  src/lib/ptree/ptree.lua
Labels: merged, release-octarina

#1457 arch/checksum: fix bug in carry propagation
  src/arch/checksum.dasl
Labels: merged, release-octarina

#1459 lib.ctable: fix hugepages allocation size
  src/lib/ctable.lua
Labels: merged, release-octarina

#1460 core.packet: fix account_free physical capacity formula
  src/core/packet.lua
Labels: bug, merged, release-octarina

#1461 Driver for Mellanox Connect-X 4/5/6 cards
  src/apps/mellanox/README.md
  src/apps/mellanox/connectx.lua
  src/apps/mellanox/connectx_test.lua
  src/apps/mellanox/trace-mlx5_core.txt.gz
  src/core/main.lua
  src/lib/hardware/README.md
  src/lib/hardware/pci.lua
Labels: enhancement, merged, mellanox, release-octarina

#1464 Tracing JIT stability improvements from lwAFTR
  lib/luajit/src/lj_trace.c
  src/core/app.lua
  src/lib/timers/ingress_drop_monitor.lua
Labels: enhancement, merged, release-octarina
