Repository snabbco/snabb, pull requests merged in 2023-11, with the labels that each got.

#1508 apps.rss, apps.ipfix: add timeline events
  src/apps/ipfix/ipfix.events
  src/apps/ipfix/ipfix.lua
  src/apps/rss/rss.events
  src/apps/rss/rss.lua
Labels: enhancement, merged, release-enigma

#1509 Fix engine.Hz mode
  src/core/app.lua
  src/lib/ptree/ptree.lua
  src/lib/scheduling.lua
Labels: bug, merged, release-enigma

#1511 apps.mellanox: add support for ConnectX-7
  src/apps/mellanox/connectx.lua
  src/lib/hardware/pci.lua
  src/program/ipfix/lib.lua
Labels: merged, release-enigma

#1512 apps.mellanox.connectx: add support for PCAM register
  src/apps/mellanox/connectx.lua
Labels: merged, release-enigma

#1517 Implement shutdown command for the config program
  src/lib/fibers/fiber.lua
  src/lib/fibers/file.lua
  src/lib/fibers/sched.lua
  src/lib/ptree/ptree.lua
  src/lib/yang/snabb-config-leader-v1.yang
  src/program/config/README
  src/program/config/README.md
  src/program/config/shutdown/README
  src/program/config/shutdown/README.inc
  src/program/config/shutdown/shutdown.lua
Labels: enhancement, merged, release-enigma

#1516 lib.hardware.pci: fix pcall in shutdown()
  src/lib/hardware/pci.lua
Labels: bug, merged, release-enigma
