Repository snabbco/snabb, pull requests merged in 2024-06, with the labels that each got.

#1524 Collected changes for June 2024 release “Faye”
  lib/luajit/src/Makefile
  lib/luajit/src/Makefile.dep
  lib/luajit/src/lib_aux.c
  lib/luajit/src/lj_alloc.c
  lib/luajit/src/lj_alloc.h
  lib/luajit/src/lj_state.c
  lib/luajit/src/lj_state.h
  src/apps/ipfix/README.templates.md
  src/apps/ipfix/http.lua
  src/apps/ipfix/ipfix-information-elements-local.inc
  src/apps/ipfix/strings.lua
  src/apps/ipfix/template.lua
  src/apps/ipfix/tls.lua
  src/apps/mellanox/connectx.lua
  src/apps/mellanox/connectx_test.lua
  src/lib/pmu_x86.dasl
Labels: release-faye

#1518 apps.mellanox.connectx: alloc_pages(): remove assertion
  src/apps/mellanox/connectx.lua
Labels: bug, merged, release-faye

#1522 Update HTTP/HTTPS IPFIX templates
  src/apps/ipfix/README.templates.md
  src/apps/ipfix/http.lua
  src/apps/ipfix/ipfix-information-elements-local.inc
  src/apps/ipfix/strings.lua
  src/apps/ipfix/template.lua
  src/apps/ipfix/tls.lua
Labels: enhancement, merged, release-faye
